configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: alb

    hostname: argocd.ajay.bar

    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/backend-protocol: HTTP

      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:076124125794:certificate/f9f8f1fa-824e-4369-abd4-51c7a3c9d4d3

      external-dns.alpha.kubernetes.io/hostname: argocd.ajay.bar
